name: Generate a build and push to another branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install all dependencies
        run: npm install

      - name: Ensure Vite is executable
        run: chmod +x node_modules/.bin/vite

      - name: Build
        run: npm run build # The build command of your project

      - name: Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "your-username"
          git checkout --orphan build
          git reset --hard
          git commit --allow-empty -m "Initializing build branch"
          git push origin build
          git checkout main
          git add dist
          git commit -m "Build assets"
          git subtree push --prefix dist origin build
